Encoding.default_external = Encoding.find('Windows-1250')
Encoding.default_internal = Encoding.find('Windows-1250') 

# usa VirtualBox come provider
VM_PROVIDER = "virtualbox"

# IP address 
IP_ADDRESS = "10.11.1.192"

# Host port per il servizio www 
HOST_PORT = 8082

Vagrant.configure("2") do |config|

  config.vm.provider VM_PROVIDER

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "web"

  config.vm.network "private_network", ip: IP_ADDRESS, virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 80, host: HOST_PORT

  # Install Puppet Agent 
  config.vm.provision :shell, path: "install-puppet.sh"

  # Provision with Puppet 
  config.vm.provision "puppet" 

end
