apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-update
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: hello 
  template: 
    metadata:
      name: hello 
      labels: 
        app: hello 
    spec:
      containers:
      - name: hello
        image: aswroma3/hello-update-kube:2023-10-v3
        readinessProbe: 
          httpGet: 
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort 
  selector:
    app: hello
  ports:
  - port: 8080
    targetPort: 8080
#     nodePort: 32083

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: hello-ing
spec:
  ingressClassName: nginx
  rules:
  - host: hello.aswroma3.it  
    http: 
      paths: 
      - pathType: Prefix
        path: /
        backend: 
          service: 
            name: hello
            port: 
              number: 8080 
              


