Encoding.default_external = Encoding.find('Windows-1250')
Encoding.default_internal = Encoding.find('Windows-1250') 

# usa VMware Workstation come provider
VM_PROVIDER = "vmware_desktop"

# IP address 
IP_ADDRESS = "10.11.2.193"

# Host port per il servizio www 
HOST_PORT = 8083

Vagrant.configure("2") do |config|

  config.vm.provider VM_PROVIDER

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "web"

  config.vm.provider "vmware_desktop" do |v| 
    v.vmx["numvcpus"] = "2"
    v.vmx["memsize"] = "1024"
    v.clone_directory = "C:/Var/VMware VMs"
    v.linked_clone = "false"
  end 

  config.vm.network "private_network", ip: IP_ADDRESS 
  config.vm.network "forwarded_port", guest: 80, host: HOST_PORT

  # Install Puppet Agent 
  config.vm.provision :shell, path: "install-puppet.sh"

  # Download Puppet modules 
  config.vm.provision :shell, path: "download-apache-puppet-modules.sh"

  # Provision with Puppet 
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "init.pp"
    puppet.module_path = "puppet/modules"
	# puppet.options = "--verbose --debug"
  end

end
