# application.yml 
---
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aswroma3/asw.git
          searchPaths: projects/config-data
          default-label: master

# usando il profilo 'native' cerca invece nel file system locale