apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-reader
#  namespace: sentence # oppure va specificato quando si fa l'apply di queste risorse
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-reader-binding
#  namespace: sentence # oppure va specificato quando si fa l'apply di queste risorse
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
