version: '3'

services:
  postgres:
    image: docker.io/postgres:latest
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
